### ISSUE TITLE
Syntax error: '.' expected after [vernac:command] (in [vernac_aux]).

### ISSUE THREAD

**Issue by hoyeunglee** [GeoCoq/GeoCoq#1]
Syntax error: '.' expected after [vernac:command](in [vernac_aux]).

when run in coqide, gott above error

do not know  where is wrong

http://coq.inria.fr/distrib/8.4pl6/stdlib/  ?

Add LoadPath "C:\Users\tester\Downloads\GeoCoq-1.0.1"

Class Hilbert := {
 Point : Type;
 Line  : Type;
 EqL   : Line -> Line -> Prop;
 EqL_Equiv : Equivalence EqL;
 Incid : Point -> Line -> Prop;

 (*\* Group I Incidence *)
 line_existence : forall A B, A<>B -> exists l, Incid A l /\ Incid B l;
 line_unicity : forall A B l m, A <> B -> Incid A l -> Incid B l -> Incid A m -> Incid B m -> EqL l m;
 two_points_on_line : forall l, exists A, exists B, Incid B l /\ Incid A l /\ A <> B;
 ColH := fun A B C => exists l, Incid A l /\ Incid B l /\ Incid C l;
 plan : exists A, exists B, exists C, ~ ColH A B C;
....

**Comment by jnarboux** [comment]
The point is missing after the Add load path command. You need also to compile the files which are in the directory GeoCoq-1.0.1 before using them let me know if you need more help.

Julien
