### ISSUE TITLE
Compilation error on 8.3pl4

### ISSUE THREAD

**Issue by hoyeunglee** [GeoCoq/GeoCoq#2]
martin@ubuntu:~/geo/GeoCoq$ ./configure.sh 
martin@ubuntu:~/geo/GeoCoq$ make
make: ocamlc.opt: Command not found
coqc  -q  -R . GeoCoq   Tarski_dev/Ch02_cong
File "/home/martin/geo/GeoCoq/Tarski_dev/Ch02_cong.v", line 90, characters 13-31:
Error: Cannot infer the implicit parameter M of
cong_commutativity.
Could not find an instance for "Tarski_neutral_dimensionless".

make: **\* [Tarski_dev/Ch02_cong.vo] Error 1

**Comment by jnarboux** [comment]
You can you give me the output of coqc -v ?
it seems that the axioms contained in Axioms/tarski_axioms are not compiled. coqdep should have computed the dependency, you should obtain something like:

```
jnarboux@coqis:~/Repository/GeoCoq$ make
"coqdep" -c -slash -R . GeoCoq "Utils/arity.v" > "Utils/arity.v.d" || ( RV=$?; rm -f "Utils/arity.v.d"; exit ${RV} )
...
"coqdep" -c -slash -R . GeoCoq "Tactics/Coinc/ColR.v" > "Tactics/Coinc/ColR.v.d" || ( RV=$?; rm -f "Tactics/Coinc/ColR.v.d"; exit ${RV} )
"coqc"  -q  -R . GeoCoq   Utils/general_tactics
Identifier 'Something' now a keyword
"coqc"  -q  -R . GeoCoq   Axioms/tarski_axioms
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch02_cong
```

**Comment by hoyeunglee** [comment]
martin@ubuntu:~/geo/GeoCoq$ coqc -v
The Coq Proof Assistant, version 8.3pl4 (April 2012)
compiled on Apr 03 2012 10:32:56 with OCaml 3.12.1
martin@ubuntu:~/geo/GeoCoq$ 
martin@ubuntu:~/geo/CoqEAL/theory$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.4 LTS
Release:    12.04
Codename:   precise

martin@ubuntu:~/geo/CoqEAL/theory$ which coq
martin@ubuntu:~/geo/CoqEAL/theory$

how to find coq binary file path?

Fetched 2,129 kB in 9s (228 kB/s)  
Selecting previously unselected package ocaml-base.
(Reading database ... 203687 files and directories currently installed.)
Unpacking ocaml-base (from .../ocaml-base_3.12.1-2ubuntu2_i386.deb) ...
Selecting previously unselected package ocaml.
Unpacking ocaml (from .../ocaml_3.12.1-2ubuntu2_i386.deb) ...
Setting up ocaml-base (3.12.1-2ubuntu2) ...
Setting up ocaml (3.12.1-2ubuntu2) ...
martin@ubuntu:~/geo/GeoCoq$ make
make: ocamlc.opt: Command not found
coqc  -q  -R . GeoCoq   Tarski_dev/Ch02_cong
File "/home/martin/geo/GeoCoq/Tarski_dev/Ch02_cong.v", line 90, characters 13-31:
Error: Cannot infer the implicit parameter M of
cong_commutativity.
Could not find an instance for "Tarski_neutral_dimensionless".

make: **\* [Tarski_dev/Ch02_cong.vo] Error 1
martin@ubuntu:~/geo/GeoCoq$

**Comment by jnarboux** [comment]
The binary for Coq is coqc.
Sorry Coq 8.3 is not supported. You need Coq version 8.4pl6.

Julien

**Comment by hoyeunglee** [comment]
i change to use  8.4p6 , thank you very much
