### ISSUE TITLE
Is GeoCoq tested with Coq 8.8?

### ISSUE THREAD

**Issue by maximedenes** [GeoCoq/GeoCoq#24]
In the `.travis.yml` file, I read that Coq's package always points to `8.7.2`. Is it a mistake?

https://github.com/GeoCoq/GeoCoq/blob/f617f66f6f5e6dfa04789aa2fd7cfa1ccf52870d/.travis.yml#L16-L18

**Comment by jnarboux** [comment]
Yes, indeed, it is a typo, thank you !
