### ISSUE TITLE
compilation error in coq8.4pl6 in ubuntu 12.04

### ISSUE THREAD

**Issue by hoyeunglee** [GeoCoq/GeoCoq#3]
martin@ubuntu:~/geo$ cd GeoCoq/
martin@ubuntu:~/geo/GeoCoq$ ls
Axioms     configure.sh  LICENSE  Makefile  Meta_theory  Tactics     Utils
Changelog  Highschool    Make     Make.in   README.md    Tarski_dev
martin@ubuntu:~/geo/GeoCoq$ ./configure.sh 
martin@ubuntu:~/geo/GeoCoq$ make
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch02_cong
File "/home/martin/geo/GeoCoq/Tarski_dev/Ch02_cong.v", line 1, characters 0-43:
Error: File /home/martin/geo/GeoCoq/Axioms/tarski_axioms.vo has bad magic
number. It is corrupted or was compiled with another version of Coq.
make: **\* [Tarski_dev/Ch02_cong.vo] Error 1
martin@ubuntu:~/geo/GeoCoq$ coqc -v
The Coq Proof Assistant, version 8.4pl6 (December 2015)
compiled on Dec 13 2015 00:21:12 with OCaml 3.12.1
martin@ubuntu:~/geo/GeoCoq$ sudo make
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch02_cong
File "/home/martin/geo/GeoCoq/Tarski_dev/Ch02_cong.v", line 1, characters 0-43:
Error: File /home/martin/geo/GeoCoq/Axioms/tarski_axioms.vo has bad magic
number. It is corrupted or was compiled with another version of Coq.
make: **\* [Tarski_dev/Ch02_cong.vo] Error 1
martin@ubuntu:~/geo/GeoCoq$

**Comment by jnarboux** [comment]
When you compile it generates .vo files. Those files depend on the version of Coq. So when you change the version of Coq you should delete all .vo first. This can be done using make clean
but as you did sudo make at some point, you may need to do sudo make clean.
The previous compilation using Coq 8.3 failed quickly so I think you should not have a lot of .vo files.
you can list them using : 
find \* | grep .vo

Hope this helps.

Julien

**Comment by hoyeunglee** [comment]
First time I install with apt-get install coq, then second time I install with tar file after apt-get remove, I do not know how make clean for the first time installation, should I uninstall current 8.4 ? How to install correctly in this case?

**Comment by jnarboux** [comment]
It seems that your ciq installation is fine. You can check the version by
typing:
coqc -v
The problem is that you still have some files files in the GeoCoq directory
compiled with the older version of coq. To remove them you need to type:
make clean

In the GeoCoq directory.

**Comment by hoyeunglee** [comment]
i understand now, i delete whole directory and git clone again
and make again , no error now,

however, it hangs at

"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/playfair_par_trans_par_perp_perp

i do not know whether it is normal? it has already run for an hour, still hangs at this line
is it really that it takes a long time?

"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/original_spp_inverse_projection
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_perp_2_par_par_perp_perp
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_perp_perp_TCP
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_perp_perp_par_perp_2_par
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_perp_perp_playfair
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_trans_playfair
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_trans_proclus
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/playfair_alternate_interior_angles
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/playfair_bis_playfair
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/playfair_par_trans_par_perp_perp

**Comment by jnarboux** [comment]
It is strange, the whole dev takes about 30 minutes to compile on my machine. The playfait_par_trans_par_perp_perp is not a particulary long file. 
Are you using a virtual machine ?

Julien

**Comment by hoyeunglee** [comment]
Yes, I was using virtual machine VMware player 12 yesterday night.

**Comment by hoyeunglee** [comment]
after increase memory and make again, it has progress now.

i have another question about how to edit setoid_rewrite?
as i can not find the implementation of setoid_rewrite, which file has this setoid_rewrite?

because i would like to edit equivalence relations into another set of relations,
does it mean that there is a need to edit all transitive axioms defined in every code file and
then make file again in order to apply new equivalence relations?

"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/original_euclid_original_spp
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/original_spp_inverse_projection
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_perp_2_par_par_perp_perp
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_perp_perp_TCP
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_perp_perp_par_perp_2_par
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_perp_perp_playfair
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_trans_playfair
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/par_trans_proclus
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/playfair_alternate_interior_angles
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/playfair_bis_playfair
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/playfair_par_trans_par_perp_perp
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/proclus_SPP
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/tarski_playfair
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/proclus_aristotle
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/proclus_bis_proclus
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/proclus_midpoints
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/tarski_euclid
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/triangle_playfair_bis
"coqc"  -q  -R . GeoCoq   Meta_theory/Parallel_postulates/Euclid
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch12_parallel_inter_dec
"coqc"  -q  -R . GeoCoq   Highschool/orientation
"coqc"  -q  -R . GeoCoq   Tarski_dev/Annexes/Tagged_predicates
"coqc"  -q  -R . GeoCoq   Tarski_dev/Annexes/quadrilaterals_inter_dec
"coqc"  -q  -R . GeoCoq   Tarski_dev/Annexes/midpoint_theorems
"coqc"  -q  -R . GeoCoq   Highschool/varignon
"coqc"  -q  -R . GeoCoq   Highschool/exercises
"coqc"  -q  -R . GeoCoq   Highschool/midpoint_thales
"coqc"  -q  -R . GeoCoq   Highschool/triangles
"coqc"  -q  -R . GeoCoq   Highschool/circumcenter
"coqc"  -q  -R . GeoCoq   Highschool/concyclic
"coqc"  -q  -R . GeoCoq   Highschool/gravityCenter
"coqc"  -q  -R . GeoCoq   Highschool/orthocenter
"coqc"  -q  -R . GeoCoq   Highschool/Euler_line
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch13_2_length
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch13_3_angles
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch13_4_cos
"coqc"  -q  -R . GeoCoq   Tarski_dev/Annexes/vectors
"coqc"  -q  -R . GeoCoq   Tarski_dev/Annexes/project
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch13_5_Pappus_Pascal
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch13_6_Desargues_Hessenberg
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch14_sum
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch14_prod
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch14_order
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch15_lengths
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch16_coordinates
"coqc"  -q  -R . GeoCoq   Tarski_dev/Ch16_coordinates_with_functions
could not prove discrimination result
could not prove discrimination result
could not prove discrimination result
could not prove discrimination result
could not prove discrimination result
could not prove discrimination result
could not prove discrimination result
could not prove discrimination result
could not prove discrimination result

could not prove discrimination result
could not prove discrimination result
could not prove discrimination result

**Comment by hoyeunglee** [comment]
i succeeded to compile and make and make install, 

is there any command to test and make use of the geocoq?

**Comment by jnarboux** [comment]
Good news. 
You can use GeoCoq to prove new theorems, you will find example of some simple proofs in highschool directory.

**Comment by hoyeunglee** [comment]
thank you very much
