### ISSUE TITLE
What books were used to make GeoCoq?

### ISSUE THREAD

**Issue by lancejpollard** [GeoCoq/GeoCoq#35]
I see [here](http://geocoq.github.io/GeoCoq/) mention of _Metamathematische Methoden in der Geometrie_ (German). Did you use that version or did you use a version in English which could be purchased online? I would like to follow along and see how the proofs/definitions/etc. were translated from natural language into Coq if possible :)

Looking forward to your response!

**Comment by jnarboux** [comment]
Dear Lance,


Unfortunately up to my knowledge there is currently no English translation of Metamathematische Methoden in der Geometrie .

But according to Michael Beeson:

"Marvelously and miraculously,  a former graduate student of Tarski
(Kenneth Driessel, who was in Tarski's seminar 1962-64 but finished 
at U. of Oregon) has stepped forward and volunteered to finance
an English translation of SST,  in the sense of paying for translation 
and putting the result into LaTeX. »

I just asked Michael if he had news about this project.

Cheers,

Julien

**Comment by Boutry** [comment]
Dear Lance, dear Julien,

I had asked Michael in early February and then Part I of the book was already translated. Michael said to the people translating it that it could be published on its own. Let's see what is new once Julien ears back from him.

Cheers,
Pierre

**Comment by Boutry** [comment]
Dear @lancejpollard,

Can I close this issue?

I could ask Michael if some translation got published.

Cheers,
Pierre

**Comment by projetmbc** [comment]
So sad...
